version: "3"
services:
  front:
    build: nginx-ghcred
    ports:
      - 8082:8082
    volumes:
      - ./docker-nginx.conf/docker-nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on:  
      - "webpack"
  webpack:
    build: node-ghcred 
    volumes:
       - ./:/usr/app/
    environment:
      - CLIENT_ID=${CLIENT_ID}
    working_dir: /usr/app/
    command: "npm run serve -- --port 8082"
