worker_processes auto;

events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout 65;

  server {
    listen 80;
    server_name _;

    # Use absolute redirects (but we control port via $redirect_host)
    absolute_redirect off;
    #port_in_redirect off;

    root   /usr/share/nginx/html;
    index  index.html;

    # Runtime variables set by 40-create-ghcred.sh
    include /GH_OAUTH_CLIENT.conf;


    # ----------------------------
    # 1) Documentation
    # ----------------------------
    location /myAppPlaceholder/docs/ {
      try_files $uri $uri/ /myAppPlaceholder/docs/404.html;
    }

    # ----------------------------
    # 2) Cartographer App
    # ----------------------------
    location /myAppPlaceholder/ {
      try_files $uri $uri/ /index.html;
    }
  }
}
